added failure type classification with testgrid data project doc to "AI for Continuous integration"
operate-first/operate-first.github.io-old pull request #112
Opened 2020-11-20 15:23 UTC by SankBad

This PR addresses [issue](https://github.com/aicoe-aiops/ocp-ci-analysis/issues/34)
I added "failure type classification with testgrid data" project doc to "AI for Continuous integration" section. 

Currently, the size of the image in the doc is small. I will update the blog once issue #111 is resolved.

You can preview the doc over [here](https://sankbad.github.io/operate-first.github.io/aici/publish/failure-type-classification-with-the-testgrid-data-project-doc)

2020-11-20 15:23 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **durandom** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @durandom` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["durandom"]} -->

2020-11-20 15:40 UTC, MichaelClifford requested changes

2020-11-20 15:40 UTC, MichaelClifford commented on content-sources.yaml
> +  dir: ocp-ci-analysis/docs
Why make this change? it just requires you to add "/publish/" to all the the href's in aico-tic.yaml? Or is this a suggestion to remove the "publish" folder all together and keep everything in "/docs"?

2020-11-20 16:38 UTC, SankBad commented on content-sources.yaml
> +  dir: ocp-ci-analysis/docs
Hi @MichaelClifford , 

Because the image used in this blog exists in the folder
`ocp-ci-analysis/docs/assets/images folder`
When I am trying to just use `dir: ocp-ci-analysis/docs/publish` in content-sources.yaml
The image was not rendering.

2020-11-20 18:53 UTC, MichaelClifford commented on content-sources.yaml
> +  dir: ocp-ci-analysis/docs
The [current documentation](https://github.com/operate-first/operate-first.github.io/blob/master/README.md#adding-remote-content) suggests keeping all artifacts to be published in the same dir. 

If this approach works, why not just use the root dir for everything? That would be the most flexible I think. Chaneg line 33 to ` dir: ocp-ci-analysis/`

@oindrillac is there a problem with using the root dir of a repo as the content source?

2020-11-20 19:39 UTC, oindrillac commented on content-sources.yaml
> +  dir: ocp-ci-analysis/docs
There was some discussion against referencing entire repos to the yaml [here](https://github.com/operate-first/operate-first.github.io/issues/52).

I see that @durandom suggested we reference directories and files explicitly from the content source. ([#52 comment](https://github.com/operate-first/operate-first.github.io/issues/52#issuecomment-724712089))

Since the way we add documentation to this repo is by configuring a "directory" in content-sources.yaml and then referencing the files we want to publish in the toc.yaml, IIUC we have to point to atleast one directory from a source repo in content-sources.yaml. The higher up we reference (for eg root of repo), the more problematic files come into the picture and there arises need to "ignore" more non-standard files from build (eg [this](https://github.com/operate-first/operate-first.github.io/issues/108) & [this](https://github.com/operate-first/operate-first.github.io/pull/48)). 

Hence we should reference just the docs directory consisting of the files to be published and ignore any problematic files from build.

2020-11-20 20:20 UTC, SankBad commented on content-sources.yaml
> +  dir: ocp-ci-analysis/docs
@MichaelClifford , Keeping `dir: ocp-ci-analysis/docs` seems good options. 
As we can maintain separate folders for images and blogs. 
Let me know If you want to change this.

2020-11-20 20:30 UTC, SankBad commented on content-sources.yaml
> +  dir: ocp-ci-analysis/docs
Otherwise, I can move the image to the  `ocp-ci-analysis/docs/publish` repo.

2020-11-20 20:55 UTC, MichaelClifford commented on content-sources.yaml
> +  dir: ocp-ci-analysis/docs
I think @oindrillac comments suggest that the higher up the content source reference the more potential issues could occur. So I think we should keep it as "docs/publish", but since the image is hosted on a public repo can't you reference the image by its github url in your doc instead of moving it?  Like below? 

`![image](https://user-images.githubusercontent.com/4494906/99848891-95745180-2b48-11eb-9a4e-f9cf5da59ab0.png)`
![image](https://user-images.githubusercontent.com/4494906/99848891-95745180-2b48-11eb-9a4e-f9cf5da59ab0.png)

2020-11-20 21:46 UTC, SankBad commented on content-sources.yaml
> +  dir: ocp-ci-analysis/docs
Sounds good!

2020-11-20 21:56 UTC, SankBad commented on content-sources.yaml
> +  dir: ocp-ci-analysis/docs
created a PR for the same. I checked this on my personal branch it's working.

2020-11-20 21:57 UTC, SankBad commented on content-sources.yaml
> +  dir: ocp-ci-analysis/docs
created a PR for the same. I checked this on my fork it's working.

2020-11-20 22:19 UTC, oindrillac commented on content-sources.yaml
> +  dir: ocp-ci-analysis/docs
Thanks @SankBad :+1:

2020-11-20 22:37 UTC, SankBad commented on content-sources.yaml
> +  dir: ocp-ci-analysis/docs
@MichaelClifford @oindrillac , 
Made all the changes.
[Preview](https://sankbad.github.io/operate-first.github.io/aici/failure-type-classification-with-the-testgrid-data-project-doc)

2020-11-21 06:58 UTC, oindrillac commented
/approve

2020-11-21 06:58 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/operate-first.github.io/pull/112#issuecomment-731519709" title="Approved">oindrillac</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)~~ [oindrillac]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-11-21 06:58 UTC, merged