Update Readme instructions
operate-first/operate-first.github.io-old pull request #118
Opened 2020-11-23 20:36 UTC by oindrillac

Updated instructions for contributing based on changes in #117

2020-11-23 20:36 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **oindrillac** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @oindrillac` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["oindrillac"]} -->

2020-11-24 10:39 UTC, tumido approved these changes
LGTM, nicely written and easy to follow! :raised_hands:

2020-11-24 10:39 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/operate-first.github.io/pull/118#pullrequestreview-537360480" title="Approved">tumido</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **oindrillac** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @oindrillac` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["oindrillac"]} -->

2020-11-24 14:13 UTC, hemajv requested changes
apart from the minor fixes, lgtm! :ship:

2020-11-24 14:13 UTC, hemajv commented on README.md
> +* **users**: Documentation for all users of ODH. Access details of various deploed ODH components.
change `deploed` to `deployed`

2020-11-24 14:13 UTC, hemajv commented on README.md
> +Add the Git source where you are adding content from. Set the name of the repo, the root ad the `dir` and set the urlPrefix as the content category you are adding that content to (see the four catego
is `the root ad` supposed to be `the root address`?

2020-11-24 14:13 UTC, hemajv commented on README.md
> +Whether adding content remotely, or locally, the content needs to be added to the vertical navigation bar on the left and belongs to one of the four categories.
`and belongs` to `should belong`?

2020-11-24 15:30 UTC, oindrillac commented on README.md
> +* **users**: Documentation for all users of ODH. Access details of various deploed ODH components.
changed

2020-11-24 15:53 UTC, oindrillac commented on README.md
> +Whether adding content remotely, or locally, the content needs to be added to the vertical navigation bar on the left and belongs to one of the four categories.
:+1:

2020-11-24 15:53 UTC, oindrillac commented on README.md
> +Add the Git source where you are adding content from. Set the name of the repo, the root ad the `dir` and set the urlPrefix as the content category you are adding that content to (see the four catego
changed

2020-11-24 15:53 UTC, oindrillac commented
@hemajv made the changes

2020-11-24 15:58 UTC, hemajv commented on README.md
> +Add the Git source where you are adding content from. Set the name of the repo, (ie. the root directory of the repo) the `dir` and set the urlPrefix as the content category you are adding that conten
should `(ie. the root directory of the repo)` come after `the dir`?

2020-11-24 16:02 UTC, oindrillac commented on README.md
> +Add the Git source where you are adding content from. Set the name of the repo, (ie. the root directory of the repo) the `dir` and set the urlPrefix as the content category you are adding that conten
ah yes, changed

2020-11-24 16:14 UTC, hemajv approved these changes
:ship:

2020-11-24 16:14 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/operate-first.github.io/pull/118#pullrequestreview-537678870" title="Approved">hemajv</a>*, *<a href="https://github.com/operate-first/operate-first.github.io/pull/118#pullrequestreview-537360480" title="Approved">tumido</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **oindrillac** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @oindrillac` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["oindrillac"]} -->

2020-11-24 16:46 UTC, merged