update data-science.yaml and Readme with new ocp-ci project links
operate-first/operate-first.github.io-old pull request #156
Opened 2020-12-09 22:34 UTC by MichaelClifford

**THIS WILL BREAK the website! if merged before [this PR](https://github.com/aicoe-aiops/ocp-ci-analysis/pull/65) on the content source repo**. Please be sure to merge both of these PR's together.  

I have proposed a reorganization of the [ocp-ci-analysis](https://github.com/aicoe-aiops/ocp-ci-analysis) repo. The reorganization resulted in file names and locations changing a bit which will prevent the content from rendering properly on the op1st website. This PR updates all the urls on the op1st site to reflect the new changes in the content source repo. 

I have also made the proper URL changes in the readme.md where they were being used as an example.

2020-12-09 22:35 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **durandom** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @durandom` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["durandom"]} -->

2020-12-10 10:45 UTC, oindrillac requested changes

2020-12-10 10:45 UTC, oindrillac commented on config/data-science.yaml
> +      href: /data-science/ocp-ci-analysis/notebooks/failure-type-classification/README.md
@MichaelClifford can please you modify this to /data-science/ocp-ci-analysis/notebooks/failure-type-classification/ instead, since the Readme files are treated as index files, the above URL would give an error.

2020-12-10 10:46 UTC, oindrillac requested changes
Added a comment, other than that, changes LGTM :)

2020-12-10 12:15 UTC, tumido commented
/approve

2020-12-10 12:15 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/operate-first.github.io/pull/156#issuecomment-742485008" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-12-10 12:16 UTC, tumido commented on config/data-science.yaml
> +      href: /data-science/ocp-ci-analysis/notebooks/failure-type-classification/README.md
Since I didn't notice the warning in the other PR, that these 2 should come together, I've fixed it for you in here so we can merge this.

2020-12-10 12:16 UTC, merged

2020-12-10 12:54 UTC, tumido commented
Build is pasing, pages are where there are supposed to be. Resolved

https://travis-ci.org/github/operate-first/operate-first.github.io/builds/748748325
https://www.operate-first.cloud/data-science/ocp-ci-analysis/notebooks/failure-type-classification/

2020-12-10 13:09 UTC, MichaelClifford commented
Thanks for the quick fix  @tumido  : ) 

This is likely a rare case, but should we put in place some additional cross-repo PR dependency checks or warnings for this type of situation in the future? Even adding a template PR form in this repo might help :man_shrugging: 

@oindrillac

2020-12-10 13:19 UTC, tumido commented
I think using the `/hold` command for bots seems sufficient for now.. But yeah, we should thing of the cross repo sync anyways (to rebuild on updates on the content repos, etc.)