Add time series pages
operate-first/operate-first.github.io-old pull request #160
Opened 2020-12-14 06:25 UTC by Shreyanand

In this PR, I add remote source for time series pages.

There are two caveats:

1) Relative links in the main page described in this [issue](https://github.com/aicoe-aiops/time-series/issues/11).
2) Rendering plotly images on the website. Currently on my local it is not able to render notebook plotly images on the website.

2020-12-14 06:25 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **martinpovolny** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @martinpovolny` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["martinpovolny"]} -->

2020-12-14 16:40 UTC, hemajv commented
@Shreyanand do you have a preview of the changes in your [Github pages](https://github.com/operate-first/operate-first.github.io#previewing-your-changes-on-github-pages)?

2020-12-14 16:48 UTC, hemajv commented on config/data-science.yaml
> +      href: /data-science/time-series/notebooks/ts-1-fetching-metrics.ipynb
isn't the notebook file name just `fetching-metrics.ipynb` according to [here](https://github.com/aicoe-aiops/time-series/blob/master/notebooks/fetching-metrics.ipynb)?

2020-12-15 06:10 UTC, Shreyanand commented on config/data-science.yaml
> +      href: /data-science/time-series/notebooks/ts-1-fetching-metrics.ipynb
Good catch! Let's wait for this [PR](https://github.com/aicoe-aiops/time-series/pull/10) to get merged :D

2020-12-15 11:48 UTC, durandom requested changes

2020-12-15 11:48 UTC, durandom commented on config/data-science.yaml
> +      href: /data-science/time-series/notebooks/ts-1-fetching-metrics.ipynb
@Shreyanand https://github.com/aicoe-aiops/time-series/pull/10 is merged, do you want to update here ?

2020-12-16 08:13 UTC, Shreyanand commented on config/data-science.yaml
> +      href: /data-science/time-series/notebooks/ts-1-fetching-metrics.ipynb
Yup! the merged PR changes the name of the file to match this.

2020-12-16 08:26 UTC, Shreyanand commented
> @Shreyanand do you have a preview of the changes in your [Github pages](https://github.com/operate-first/operate-first.github.io#previewing-your-changes-on-github-pages)?

@hemajv It is working fine on my local but when I run make gh-pages-fork, the content published on https://shreyanand.github.io/operate-first.github.io has the side navigation links missing. I'm not sure why that's happening because the changes in this PR seem ok and it works fine on my local.

2020-12-17 19:09 UTC, hemajv commented
> > @Shreyanand do you have a preview of the changes in your [Github pages](https://github.com/operate-first/operate-first.github.io#previewing-your-changes-on-github-pages)?
> 
> @hemajv It is working fine on my local but when I run make gh-pages-fork, the content published on https://shreyanand.github.io/operate-first.github.io has the side navigation links missing. I'm not sure why that's happening because the changes in this PR seem ok and it works fine on my local.

ah yes, I think @aakankshaduggal had the same issue as well. Seems like sometimes the github pages preview is broken. I do see your changes at https://shreyanand.github.io/operate-first.github.io/data-science/time-series/ though.

2020-12-17 19:13 UTC, SankBad commented
I also had the same issue a week back.

2020-12-17 19:21 UTC, hemajv approved these changes
lgtm :ship:

2020-12-17 19:21 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/operate-first.github.io/pull/160#pullrequestreview-554914869" title="Approved">hemajv</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **martinpovolny** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @martinpovolny` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["martinpovolny"]} -->

2021-01-04 12:51 UTC, tumido approved these changes

2021-01-04 12:51 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/operate-first.github.io/pull/160#pullrequestreview-554914869" title="Approved">hemajv</a>*, *<a href="https://github.com/operate-first/operate-first.github.io/pull/160#pullrequestreview-561005971" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-01-04 12:51 UTC, merged