feat: Add Mailing list analysis initial content
operate-first/operate-first.github.io-old pull request #175
Opened 2021-01-13 15:50 UTC by tumido

Content will be available at https://www.operate-first.cloud/data-science/mailing-list-analysis/

2021-01-13 15:50 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **tumido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @tumido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2021-01-13 16:08 UTC, MichaelClifford approved these changes
LGTM

2021-01-13 16:08 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/operate-first.github.io/pull/175#pullrequestreview-567381678" title="Approved">MichaelClifford</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **tumido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @tumido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2021-01-13 16:09 UTC, oindrillac requested changes
Changes look good :tada: :+1: 
Added one comment.

2021-01-13 16:09 UTC, oindrillac commented on content/data-science/index.md
> +9. **Mailing list Analysis**: This analysis contains example code for how to develop a custom end-to-end email analytics service using the Open Data Hub on OpenShift. We demonstrate this on a text an
@tumido this list is alphabetically ordered. So could we move this item to number 5?

Also could we rephrase the second sentence as -
`We demonstrate this by performing text analysis on the Fedora mailing list.`

2021-01-15 08:33 UTC, sesheta commented
@tumido: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-01-15 08:45 UTC, tumido commented on content/data-science/index.md
> +9. **Mailing list Analysis**: This analysis contains example code for how to develop a custom end-to-end email analytics service using the Open Data Hub on OpenShift. We demonstrate this on a text an
Done :+1:

2021-01-15 12:46 UTC, oindrillac approved these changes
:ship:

2021-01-15 12:46 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/operate-first.github.io/pull/175#pullrequestreview-567381678" title="Approved">MichaelClifford</a>*, *<a href="https://github.com/operate-first/operate-first.github.io/pull/175#pullrequestreview-569228931" title="Approved">oindrillac</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)~~ [oindrillac]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-01-15 12:47 UTC, merged