`pet-image-detection` added to data science section
operate-first/operate-first.github.io-old pull request #225
Opened 2021-03-29 16:20 UTC by isabelizimm

created "Other Projects" tab under Data Science, added [https://github.com/aicoe-aiops/pet-image-detection](https://github.com/aicoe-aiops/pet-image-detection)

2021-03-29 16:52 UTC, oindrillac commented
What would be the goal of including this in an "Other Projects" tab in the data science side panel and not in the main tab?
cc: @isabelizimm @MichaelClifford

2021-03-29 17:29 UTC, MichaelClifford requested changes

2021-03-29 17:29 UTC, MichaelClifford commented on config/data-science.yaml
> +- label: Other Projects
I don't think we need to create a new "Other Projects" section. Can you add this to the "Data Science Projects" tab at the top?

2021-03-30 13:00 UTC, isabelizimm commented
> What would be the goal of including this in an "Other Projects" tab in the data science side panel and not in the main tab?
> cc: @isabelizimm @MichaelClifford

My goal was to have a collecting point for all smaller projects that exist as just 1 notebook or so to compartmentalize. I updated it to be its own header.

2021-03-30 13:00 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **martinpovolny** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @martinpovolny` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["martinpovolny"]} -->

2021-03-30 13:06 UTC, MichaelClifford commented
@isabelizimm It's still unclear to me why this needs its own section? There is already a Data Science Projects tab that contains smaller projects. I think it would be appropriate to add your work there. : )

2021-03-30 13:41 UTC, isabelizimm commented
That works for me! I'm okay with it wherever it fits best :D

2021-04-01 18:09 UTC, aakankshaduggal commented
@isabelizimm I have added some changes to this file, please make sure to `git pull --rebase upstream master` before you push your updates :smile:

2021-04-12 12:20 UTC, isabelizimm commented
/assign @martinpovolny
(does this need to be changed with Martin's move?)

2021-04-12 14:43 UTC, oindrillac reviewed
since @isabelizimm has 2 docs to add, having a separate section should be fine.
/lgtm

2021-04-14 19:37 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by:

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["oindrillac"]} -->

2021-04-14 19:37 UTC, merged