Add in a link to a Code of Conduct
operate-first/operate-first.github.io-old pull request #244
Opened 2021-04-29 05:11 UTC by quaid

If the OIF Code of Conduct is the wrong one, what is the correct one?

This should be easily findable in the footer or a main menu, depending on information architecture of the site.

I am proposing this link in this location as my best guest of what CoC to use and where to put the link.

If there should be a different CoC or location for the link, feel free to use this merge request to and patch it for the correct info.

2021-04-29 05:12 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **tumido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @tumido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2021-04-29 08:02 UTC, tumido requested changes

2021-04-29 08:02 UTC, tumido commented on src/components/Layout/Footer.js
> +        Creator of Operate-First Logo
Please fix the link text

2021-04-30 16:37 UTC, durandom commented on src/components/Layout/Footer.js
> +        Creator of Operate-First Logo
just "Code of Conduct" ?

2021-04-30 16:39 UTC, durandom commented
I have no idea which CoC to use 🤣 🤷‍♂️
If the Openstack one is a good one, just use that, sounds reasonable.
Is there one we could fork? Like you would fork a style-guide?

2021-05-01 01:35 UTC, quaid commented on src/components/Layout/Footer.js
> +        Creator of Operate-First Logo
Is there something unclear about the link text?

The link is to serve two purposes—show people we have a code of conduct (people look for it when they come to a project), and if you need to read or use the CoC, there it is. I _think_ the link text of "Code of Conduct" is conveys that, but perhaps there is a more clear way to accomplish that?

2021-05-01 01:55 UTC, quaid commented
> I have no idea which CoC to use rofl man_shrugging
> If the Openstack one is a good one, just use that, sounds reasonable.
> Is there one we could fork? Like you would fork a style-guide?

Here is my reasoning:

* There is a clear association/relationship with this project and the openinfra.dev.
* Open Infra Labs uses the Openstack CoC.
* It looks to me like a good CoC, derived from CoCs with a good heritage.
* It is adopted across the entire Open Infra Foundation hosted projects.
* It's easier to adopt the CoC of sibling community than to create one from scratch.
* Adopting the OpenStack CoC keeps things compatible in common spaces.

That reasoning all said, another viewpoint is to look to the Kubernetes CoC instead.

https://kubernetes.io/community/code-of-conduct/

That one has a provenance going to the Contributor Covenant, which is a very popular starting point for CoCs. The k8s community one is actually derived from the CNCFs.

So, that all said, what is the governance in this community to make a decision around which code of conduct is The Code of Conduct? (I was just guessing, too.)

Finally, as for where it should be linked, I'm not sure the footer is the best place, but it's somewhere to put it for now (presuming the project is adopting one.)

2021-05-03 12:19 UTC, tumido requested changes

2021-05-03 12:19 UTC, tumido commented on src/components/Layout/Footer.js
> +        Creator of Operate-First Logo
Sorry, I should have explained myself better here.
1. You're correctly setting the `aria-label` to `Code of Conduct`.
2. The visible link text is left as `Creator of Operate-First Logo`. And that's what appears on the site if you render it/start it:

![image](https://user-images.githubusercontent.com/7453394/116875014-82e36580-ac1a-11eb-8756-683bb3f7e60e.png)

2021-05-04 01:08 UTC, quaid commented on src/components/Layout/Footer.js
> +        Creator of Operate-First Logo
Oh my, yes, thank you, I was indeed not parsing the markup correctly, I'll fix the patch.

2021-05-04 01:09 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **durandom** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @durandom` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["durandom"]} -->

2021-05-04 01:10 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **durandom** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @durandom` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["durandom"]} -->

2021-05-04 01:52 UTC, HumairAK commented
/lgtm

2021-05-04 14:08 UTC, tumido reviewed
/lgtm

@durandom can you please approve if you agree with the code of conduct choice? I have really no expertise in this. In my view I'd like to keep us rather closer to CNCF than OpenStack simply due to the nature of the projects we colaborate with mostly, but I really don't understand the implications at all.

2021-05-04 14:58 UTC, durandom commented
/approve

2021-05-04 14:58 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/operate-first.github.io/pull/244#issuecomment-832008672" title="Approved">durandom</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)~~ [durandom]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-05-04 14:59 UTC, merged