Linking in new mailing lists
operate-first/operate-first.github.io-old pull request #298
Opened 2021-08-21 04:20 UTC by quaid

These key mailing lists are worthy of being on the front page, at least for now.

2021-08-21 04:20 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **quaid** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["quaid"]} -->

2021-08-23 10:44 UTC, tumido requested changes
@quaid I think you're including changes from #290 PR in here as well.

2021-10-19 13:12 UTC, harshad16 commented
/test all

2021-10-20 08:52 UTC, durandom commented
@quaid is the PR still relevant?

2021-12-07 03:49 UTC, quaid commented
overcome by other PRs that made the same fix

2021-12-07 03:49 UTC, closed without merging