create community tab + pages
operate-first/operate-first.github.io-old pull request #315
Opened 2021-10-19 15:26 UTC by isabelizimm

Create community tab, bring in community metrics and code of conduct to be easily found on the site.

2021-10-19 15:49 UTC, oindrillac approved these changes
/lgtm 👍 
/approve

2021-10-19 16:10 UTC, harshad16 commented
/test all

2021-10-19 17:00 UTC, tumido approved these changes
/lgtm
/approve

2021-10-20 08:50 UTC, durandom requested changes

2021-10-20 08:50 UTC, durandom commented on content/community/index.md
> +If you're interested in data science, check out our [data science projects](https://www.operate-first.cloud/data-science/projectsoverview.md). If you are more interested in site reliabilty engineerin
let's make the links relative, ie. remove the `https://www.operate-first.cloud/` portion

2021-10-20 08:50 UTC, durandom commented
/cc @quaid

2021-11-02 13:05 UTC, isabelizimm commented
@tumido @oindrillac bumping this :)

2021-11-02 13:24 UTC, aakankshaduggal reviewed
/lgtm
/approve

2021-11-03 16:28 UTC, tumido commented
Prow not merging this repo, so I'm gonna merge it manually. :slightly_smiling_face:

2021-11-03 16:28 UTC, merged