wip: feat: Add Gitub actions for deploying website
operate-first/operate-first.github.io-old pull request #333
Opened 2021-11-24 11:02 UTC by mimotej

Migrate automatic builds of website from Travis to GitHub actions using https://github.com/marketplace/actions/github-pages-action . 
Part of: https://github.com/operate-first/hitchhikers-guide/issues/112

2021-11-24 11:56 UTC, tumido requested changes

2021-11-24 11:56 UTC, tumido commented on .github/workflows/build_job.yaml
> +                   node-version: '14'
We need node 12, see the `.travis.yml`

2021-11-24 11:56 UTC, tumido commented on .github/workflows/build_job.yaml
> +               if: ${{ github.ref == 'refs/heads/main' }}
This repo uses `master` branch. Not sure if the `if` statement is even needed if this workflow is triggered by push to master only.

2021-11-24 11:56 UTC, tumido commented on .github/workflows/build_job.yaml
> +              group: ${{ github.workflow }}-${{ github.ref}}
I think we want always only a single instance of this - you want to hardcode a value in here, instead of variables and add 
 `cancel-in-progress`.

https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency

2021-11-24 11:56 UTC, tumido commented on .github/workflows/build_job.yaml
> +          runs-on: ubuntu-20.04
Can we run latest?

2021-11-24 11:56 UTC, tumido commented on .github/workflows/build_job.yaml
> +             - run: npm build
```suggestion
             - run: npm run build
```

`npm build` no longer exist since npm v7, better use `npm run build` (the former `npm build` translates to the the same)

2021-11-24 11:56 UTC, tumido commented on .github/workflows/build_job.yaml
> +                    cname: operate-first.cloud
https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-add-cname-file-cname

cname already exists here https://github.com/operate-first/operate-first.github.io/blob/master/static/CNAME

Let's keep only one (and use the same value please)

2021-11-24 13:16 UTC, mimotej commented on .github/workflows/build_job.yaml
> +                   node-version: '14'
Resolved in latest commit.

2021-11-24 13:16 UTC, mimotej commented on .github/workflows/build_job.yaml
> +               if: ${{ github.ref == 'refs/heads/main' }}
Resolved in latest commit.

2021-11-24 13:16 UTC, mimotej commented on .github/workflows/build_job.yaml
> +              group: ${{ github.workflow }}-${{ github.ref}}
Resolved in latest commit.

2021-11-24 13:17 UTC, mimotej commented on .github/workflows/build_job.yaml
> +          runs-on: ubuntu-20.04
Resolved in latest commit.

2021-11-24 13:17 UTC, mimotej commented on .github/workflows/build_job.yaml
> +             - run: npm build
Resolved in latest commit.

2021-11-24 13:17 UTC, mimotej commented on .github/workflows/build_job.yaml
> +                    cname: operate-first.cloud
Resolved in latest commit.

2021-11-24 14:26 UTC, tumido commented on .github/workflows/build_job.yaml
> +              group: ${{ github.workflow }}-${{ github.ref}}
`cancel-in-progress` is a property, not a group name, please read the linked docs

2021-11-24 14:26 UTC, tumido requested changes
See https://github.com/operate-first/operate-first.github.io/pull/333#discussion_r756127369

2021-11-25 14:58 UTC, tumido approved these changes
/lgtm
/approve

2021-11-25 15:03 UTC, merged