new top level navigation
operate-first/operate-first.github.io-old pull request #369
Opened 2022-04-13 10:28 UTC by durandom

cc @HumairAK @quaid @stefwrite @oindrillac @schwesig 

we probably want to have _some_ content in those subpages and links to previous content

fixes https://github.com/operate-first/operate-first.github.io/issues/367

2022-04-13 16:34 UTC, oindrillac requested changes
@durandom changing 
content/data-science/index.md → content/community/data-science.md will break the current link https://www.operate-first.cloud/data-science. 
Can we create a redirect for www.operate-first.cloud/data-science to go to www.operate-first.cloud/community/data-science.md ? or keep the markdown where it is? so that any existing backlinks to /data-science do not break.

2022-04-13 16:34 UTC, oindrillac commented on config/community.yaml
> +- label: Data Sciene Community
```suggestion
- label: Data Science Community
```

2022-04-13 16:34 UTC, oindrillac commented on content/community/data-science.md
> +I’m a **software engineering manager** and I need to integrate a few data scientists and their ML models into our product, but I don’t know where to start. Take a look at our [DS Workflow](/data-scie
```suggestion
I’m a **software engineering manager** and I need to integrate a few data scientists and their ML models into our product, but I don’t know where to start. Take a look at our [DS Workflow](/data-science/ds-workflows/README.md) docs.
```

2022-04-13 16:43 UTC, oindrillac commented
Existing data-science content and the [operate first data science community meetup landing page](https://www.operate-first.cloud/data-science/operate-first-data-science-community/docs/meetup-landing-page.md) are not directly navigable through the new UI. We should think about what all we want to show and how we want to restructure the documentation.

![image](https://user-images.githubusercontent.com/32435206/163229132-942b7214-a51d-4540-b573-8f9c3e6a2577.png)

My proposal is to make this page ^ into a drop down and have the current "Get Involved" section under it which to show the Data Science Community Meetup landing page and also update the landing page to link the meetup within the CTAs under the "Who are you" section.
 
cc: @MichaelClifford @aakankshaduggal

2022-04-14 12:09 UTC, MichaelClifford commented
I agree with @oindrillac I think the important navigable pages at this point are:

* https://www.operate-first.cloud/data-science/
* https://www.operate-first.cloud/data-science/operate-first-data-science-community/docs/meetup-landing-page.md
* https://www.operate-first.cloud/data-science/operate-first-data-science-community/docs/content.md

2022-04-21 13:39 UTC, closed without merging