Operate First in Action
operate-first/operate-first.github.io-old pull request #372
Opened 2022-04-25 18:40 UTC by aakankshaduggal

For https://github.com/operate-first/operate-first-in-action/issues/5

2022-04-25 18:50 UTC, oindrillac commented on gatsby-config.js
> +  {
Could we do redirect to the Jupyterbook we created instead of generating the Page from the Repo?

2022-04-25 18:50 UTC, oindrillac commented on src/components/Layout/Header.js
> +    ['action', 'Action'],
Is the top Nav bar the right location to link this from the site? Should the www.operate-first.cloud/action/ landing JB be linked from somewhere else instead? Maybe a CTA on the homepage? "See Operate First in Action", and we have a direct shareable link.

@durandom wdyt?

2022-04-25 18:54 UTC, aakankshaduggal commented on gatsby-config.js
> +  {
Yes yes, adding it. We are facing some issues with jupyterbook, hence still a WIP.

2022-04-25 19:34 UTC, aakankshaduggal commented on config/action.yaml
> +      remote: https://www.operate-first.cloud/operate-first-in-action/
Adding this link as a placeholder since the meteor book is not working at the moment.

2022-04-26 15:53 UTC, durandom commented
cant we just add an `action.md` file with the redirect directive? Like in https://github.com/operate-first/operate-first.github.io/search?q=redirect%3A&type=code

2022-04-26 15:54 UTC, durandom commented on src/components/Layout/Header.js
> +    ['action', 'Action'],
Nope, let's not add it to the navigation itself

2022-04-26 16:07 UTC, durandom commented
actually that doesnt work :( 

but adding the same to `action/index.md` should work

2022-04-26 16:12 UTC, aakankshaduggal commented
Thanks @durandom, hoping this works :+1:

2022-04-26 16:13 UTC, durandom commented
like https://www.operate-first.cloud/code_of_conduct

2022-04-26 16:15 UTC, durandom reviewed
only the `.md` file is needed

2022-04-26 16:23 UTC, durandom requested changes

2022-04-26 16:23 UTC, durandom commented on content/action/index.md
> +---
Ok. If that works I would also add some content with the link, so that if the redirect doesn't work, users can still click

2022-04-26 16:24 UTC, aakankshaduggal commented on content/action/index.md
> +---
Sounds good.

2022-04-26 17:42 UTC, oindrillac approved these changes
/lgtm

2022-05-03 16:14 UTC, sesheta commented
New changes are detected. LGTM label has been removed.

2022-05-03 16:19 UTC, tumido approved these changes
/lgtm
/approve

2022-05-06 13:34 UTC, schwesig approved these changes
/lgtm
/approve

2022-05-06 14:26 UTC, durandom approved these changes
/lgtm
/approve

2022-05-06 15:11 UTC, merged