added configuration file analysis blog
operate-first/operate-first.github.io-old pull request #47
Opened 2020-10-21 17:35 UTC by SankBad

This PR will add entry in toc.yaml and content-sources.yaml files for configuration file analysis blog. 
We used remote repo([src](https://github.com/aicoe-aiops/configuration-files-analysis)) for adding this blog. 
I tested the site locally and it looks as expected.

2020-10-21 17:35 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign  after the PR has been reviewed.
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-10-22 14:06 UTC, oindrillac requested changes
@SankBad I get an error from the ssh url in the content-sources.yaml (when I try to build without manually cloning the repo). Can you replace it with https://github.com/aicoe-aiops/configuration-files-analysis.git?

2020-10-22 14:06 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-10-22 14:06 UTC, sesheta commented
@SankBad: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-10-22 14:22 UTC, SankBad commented
@oindrillac , Thanks for pointing out.
I changed ssh key to a web url.

2020-10-22 14:28 UTC, oindrillac commented
@SankBad I think the ignore key added in #48 for the continuous-deployment repo got moved. can you please move it back?

2020-10-22 14:50 UTC, SankBad commented
Hi @oindrillac , 

ignore key is available in this PR. 
I rebase my repo before making the changes.

2020-10-22 15:57 UTC, cfchase requested changes

2020-10-22 15:57 UTC, cfchase commented on content-sources.yaml
> +  urlPrefix: config_analysis
I would stick with dash `config-analysis` instead of `config_analysis` in urls just to be consistent

2020-10-22 16:12 UTC, SankBad commented
@cfchase @oindrillac 
Thanks for the feedback. 
I fixed the format of urlPrefix and changed the location of ignore key.
Also, squashed the commits.

2020-10-22 17:30 UTC, cfchase requested changes

2020-10-22 17:30 UTC, cfchase commented on content-sources.yaml
> +
add `configuration-files-analysis`  in the Remote Content section in the [`.gitignore`](https://github.com/operate-first/operate-first.github.io/blob/master/.gitignore#L2)

2020-10-22 17:30 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign  after the PR has been reviewed.
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-10-22 17:41 UTC, SankBad commented
Hi @cfchase ,

Added entry in the [`.gitignore`](https://github.com/operate-first/operate-first.github.io/blob/master/.gitignore#L2) file

2020-10-22 17:44 UTC, cfchase approved these changes

2020-10-22 17:44 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/operate-first.github.io/pull/47#pullrequestreview-514973876" title="Approved">cfchase</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-10-22 17:51 UTC, oindrillac approved these changes

2020-10-22 17:51 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/operate-first.github.io/pull/47#pullrequestreview-514973876" title="Approved">cfchase</a>*, *<a href="https://github.com/operate-first/operate-first.github.io/pull/47#pullrequestreview-514978990" title="Approved">oindrillac</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign  after the PR has been reviewed.
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-10-22 17:52 UTC, merged