Add MOC page
operate-first/operate-first.github.io-old pull request #61
Opened 2020-10-30 20:10 UTC by hemajv

This addresses #59 

You can view the changes here:

1. [Getting Access to MOC doc](https://hemajv.github.io/operate-first.github.io/moc-cnv/about-the-cluster)
2. [MOC Getting Started doc](https://hemajv.github.io/operate-first.github.io/odh-moc/getting-started-moc)

2020-10-30 20:10 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **durandom** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @durandom` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["durandom"]} -->

2020-10-30 20:54 UTC, oindrillac reviewed
@hemajv thanks for taking this up. can you please share your gh pages test preview

2020-10-30 21:07 UTC, oindrillac commented
Oh nvm. I realized the urls point to the test deployment :slightly_smiling_face:

2020-10-30 21:15 UTC, oindrillac requested changes
@hemajv added a comment. Can we also add a link to the JupyterHub URL somewhere in the getting-started-moc doc?

2020-10-30 21:15 UTC, oindrillac commented on content/odh-moc/getting-started-moc/index.md
> +1. First, you will need to get access to the MOC CNV cluster. Follow instructions in [Getting Access](/getting-access) for this.
@hemajv the Getting Access url throws a 404. I believe it would have to be pointed to the getting-access href which is /moc-cnv/about-the-cluster

2020-10-30 21:20 UTC, oindrillac commented
@hemajv the getting-started doc is a very useful doc. maybe it should also be on https://github.com/operate-first/odh-moc-support. Is it better to maintain it there instead and link it from the remote repo? WDYT?

2020-11-02 15:00 UTC, hemajv commented on content/odh-moc/getting-started-moc/index.md
> +1. First, you will need to get access to the MOC CNV cluster. Follow instructions in [Getting Access](/getting-access) for this.
@oindrillac thanks for pointing that out, will update it :+1:

2020-11-02 15:02 UTC, hemajv commented
> @hemajv the getting-started doc is a very useful doc. maybe it should also be on https://github.com/operate-first/odh-moc-support. Is it better to maintain it there instead and link it from the remote repo? WDYT?

Yes, I think that would be a good place to have it. I can move it over there

2020-11-02 15:03 UTC, hemajv commented
> @hemajv added a comment. Can we also add a link to the JupyterHub URL somewhere in the getting-started-moc doc?
The current JupyterHub URL will be changed soon, so once the deployment is finalized I'll include the link to the updated URL

2020-11-03 21:48 UTC, hemajv commented
updated the MOC page to pull the docs from the https://github.com/operate-first/odh-moc-support as a remote repo
cc @HumairAK @oindrillac

2020-11-03 21:56 UTC, HumairAK commented
lgtm!

2020-11-04 14:44 UTC, oindrillac approved these changes
:ship:

2020-11-04 14:44 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/operate-first.github.io/pull/61#pullrequestreview-523428636" title="Approved">oindrillac</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **durandom** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @durandom` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["durandom"]} -->

2020-11-04 14:46 UTC, merged