modified landing page content
operate-first/operate-first.github.io-old pull request #67
Opened 2020-11-04 16:41 UTC by oindrillac

Added some more context to the landing page.
Addresses #45 

Please give your inputs.

Question: Should I move Roles & Phases to a separate doc?

2020-11-04 16:41 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cfchase** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @cfchase` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["cfchase"]} -->

2020-11-04 18:39 UTC, aakankshaduggal requested changes

2020-11-04 18:39 UTC, aakankshaduggal commented on content/operate-first/index.md
>  ## Phases
@oindrillac In my opinion we can keep them in separate docs. Because with the description, it looks like a great landing page.

2020-11-07 13:10 UTC, durandom approved these changes
LGTM

2020-11-07 13:10 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/operate-first.github.io/pull/67#pullrequestreview-525652050" title="Approved">durandom</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first.github.io).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/operate-first.github.io/blob/master/OWNERS)~~ [durandom]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-11-07 13:11 UTC, merged